name: Run Tests and Send Email on Failure

on:
  push:
    branches:
      - master  # Change if using a different branch
  pull_request:
    branches:
      - master

jobs:
  test-and-report:
    runs-on: windows-latest  # Using Windows runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x  # Adjust based on your project

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --no-restore --configuration Debug

      - name: Run Tests
        id: run-tests
        run: dotnet test --logger trx
        continue-on-error: true  # Ensures next steps execute even if tests fail

      - name: Upload Failed Screenshots
        if: failure()  # Runs only if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: failed-screenshots
          path: SauceHappy/bin/Debug/net6.0/Reports/Screenshots/*.png
          if-no-files-found: warn  # Prevents failure if screenshots are missing

      - name: Send Email with Test Report & Screenshots
        if: failure()  # Runs only if tests fail
        run: dotnet test --filter "SauceHappy.Hooks1.Hooks.SendEmailWithGmail"
